apiVersion: v1
kind: Secret
metadata:
  name: airflow-db-secret
  namespace: airflow
type: Opaque
data:
  AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: cG9zdGdyZXNxbCtwc3ljb3BnMjovL2FpcmZsb3d1c2VyOlNlY3VyZVBhc3MxMjMhQHBvc3RncmVzLW1sb3BzLWFudWJoLnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbTo1NDMyL2FpcmZsb3c= # base64-encoded "postgresql+psycopg2://airflowuser:SecurePass123!@postgres-mlops-anubh.postgres.database.azure.com:5432/airflow"