apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: airflow-task-role
  namespace: default
rules:
  - apiGroups: [""]
    resources: ["pods", "pods/log", "configmaps", "secrets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: airflow-task-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: airflow-sa
    namespace: airflow
roleRef:
  kind: Role
  name: airflow-task-role
  apiGroup: rbac.authorization.k8s.io