apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-pod-template
  namespace: airflow
data:
  pod_template.yaml: |
    apiVersion: v1
    kind: Pod
    metadata:
      namespace: airflow
    spec:
      serviceAccountName: airflow-sa
      containers:
      - name: base
        image: mlopsacrvs5tyf.azurecr.io/airflow:latest
        imagePullPolicy: Always
        env:
          - name: AIRFLOW__CORE__EXECUTOR
            value: KubernetesExecutor
          - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            valueFrom:
              secretKeyRef:
                name: airflow-db-secret
                key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
          - name: AIRFLOW__SECRETS__BACKEND
            value: "airflow.providers.microsoft.azure.secrets.key_vault.AzureKeyVaultBackend"
          - name: AIRFLOW__SECRETS__BACKEND_KWARGS
            value: '{"vault_url": "https://mlops-keyvault-anubh.vault.azure.net/", "credential_type": "managed_identity"}'
          - name: AIRFLOW__LOGGING__REMOTE_LOGGING
            value: "true"
          - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
            value: "azure_default"
          - name: MLFLOW_URI
            value: "http://mlflow:5000"
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
          - name: logs
            mountPath: /opt/airflow/logs
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
      imagePullSecrets:
        - name: acr-secret