apiVersion: v1
kind: Namespace
metadata:
  name: airflow
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-dags-pvc
  namespace: airflow
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: azurefile-rwx-new
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airflow-logs-pvc
  namespace: airflow
spec:
  accessModes: ["ReadWriteMany"]
  storageClassName: azurefile-rwx-new
  resources:
    requests:
      storage: 10Gi