apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      serviceAccountName: airflow-sa

      # ✅ Init container to fix logs permissions
      initContainers:
        - name: init-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 50000:50000 /opt/airflow/logs"]
          volumeMounts:
            - name: logs
              mountPath: /opt/airflow/logs

      containers:
        - name: scheduler
          image: mlopsacrvs5tyf.azurecr.io/airflow:latest
          command: ["airflow", "scheduler"]
          env:
            - name: AIRFLOW__CORE__EXECUTOR
              value: "KubernetesExecutor"
            - name: AIRFLOW__KUBERNETES__NAMESPACE
              value: "airflow"
            - name: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
              valueFrom:
                secretKeyRef:
                  name: airflow-db-secret
                  key: AIRFLOW__DATABASE__SQL_ALCHEMY_CONN
            - name: AIRFLOW__SECRETS__BACKEND
              value: "airflow.providers.microsoft.azure.secrets.key_vault.AzureKeyVaultBackend"
            - name: AIRFLOW__SECRETS__BACKEND_KWARGS
              value: '{"vault_url": "https://mlops-keyvault-anubh.vault.azure.net/", "credential_type": "managed_identity"}'
            - name: AIRFLOW__LOGGING__REMOTE_LOGGING
              value: "true"
            - name: AIRFLOW__LOGGING__REMOTE_LOG_CONN_ID
              value: "azure_default"
            - name: MLFLOW_URI
              value: "http://mlflow:5000"
          volumeMounts:
            - name: dags
              mountPath: /opt/airflow/dags
            - name: logs
              mountPath: /opt/airflow/logs
            - name: pod-template
              mountPath: /opt/airflow/pod_template.yaml
              subPath: pod_template.yaml

      securityContext:
        runAsUser: 0       # run container as root
        fsGroup: 50000     # allow shared volume access

      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
        - name: pod-template
          configMap:
            name: airflow-pod-template

      imagePullSecrets:
        - name: acr-secret
