# k8s/airflow-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-scheduler
  namespace: airflow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: scheduler
        image: mlopsacrvs5tyf.azurecr.io/airflow:latest
        env:
          - name: AIRFLOW__CORE__LOAD_EXAMPLES
            value: "False"
          - name: AIRFLOW__CORE__EXECUTOR
            value: "KubernetesExecutor"
          - name: DATABRICKS_TOKEN
            valueFrom:
              secretKeyRef:
                name: airflow-secrets
                key: databricks_token
          - name: MLFLOW_URI
            value: "http://mlflow:5000"
        volumeMounts:
          - name: dags
            mountPath: /opt/airflow/dags
          - name: logs
            mountPath: /opt/airflow/logs
      volumes:
        - name: dags
          persistentVolumeClaim:
            claimName: airflow-dags-pvc
        - name: logs
          persistentVolumeClaim:
            claimName: airflow-logs-pvc
