apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: azurefile-rwx-new
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS
reclaimPolicy: Retain
volumeBindingMode: Immediate