apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: airflow
  name: pod-creator
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-creator-binding
  namespace: airflow
subjects:
- kind: ServiceAccount
  name: airflow-sa
  namespace: airflow
roleRef:
  kind: Role
  name: pod-creator
  apiGroup: rbac.authorization.k8s.io